apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1  # Usually, you have one MongoDB instance per pod
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb 
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4.25  # Replace with your MongoDB image
        ports:
        - containerPort: 27017  # Default MongoDB port